name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Use cached node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            node-modules-

      - name: Install Dependencies
        run: bun install

      - name: Publish to npm
        run: bun publish --access public
        env:
          BUN_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Create GitHub release
        run: bunx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Attach Binaries
        uses: stacksjs/action-releaser@v1.1.0
        with:
          files: |
            bin/localtunnels-linux-x64.zip
            bin/localtunnels-linux-arm64.zip
            bin/localtunnels-windows-x64.zip
            bin/localtunnels-darwin-x64.zip
            bin/localtunnels-darwin-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
